component_depth: 2
languages:
- name: python
  production:
    exclude:
      - docs/.*
  test:
    include:
      - tests/
      - desolver/backend/tests/*
      - desolver/exception_types/tests/*
      - desolver/utilities/tests/*
      - desolver/tests/*
