component_depth: 2
languages:
    - python
    test:
        include:
          - tests/
          - desolver/backend/tests/*
          - desolver/exception_types/tests/*
          - desolver/utilities/tests/*
          - desolver/tests/*

exclude:
- /docs/.*