# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests/coverage
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830 # v3.1.1 pinned commit
      continue-on-error: true
      with:
        miniforge-version: latest
        auto-update-conda: true
        channels: conda-forge, pytorch
        python-version: ${{ matrix.python-version }}
    - name: Output conda info
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement build-requirements.txt
    - name: Test All backend
      run: hatch test --all --cover -- -vx
    - name: Upload Coverage report
      run: codecov coverage
  publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: "3.12"
      - name: Install pypa/build
        run: python -m pip install --requirements build-requirements.txt
      - name: Build a binary wheel and a source tarball
        run: hatch build
      - name: Publish distribution 📦 to Test PyPI
        if: startsWith(github.ref, 'refs/tags/test_v')
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/